name = input("enter your name: ")
branch = ("enter your branch: ")
gender = ("enter your gender: ")
collegeName = input("college name: ")
age = int(input("enter your age: "))
print("Name:",name)
print("branch:",branch)
print("gender",gender)
print("college name",collegeName)
print("age:,age)
